@baseURL = http://0.0.0.0:1234/api

# @name getAllCategories
GET {{baseURL}}/categories

###

# @name getCategory
GET {{baseURL}}/categories/d3c19ef0-c348-486a-aef3-7ab67694541f

###

# @name addCategory
POST {{baseURL}}/categories
Content-Type: application/json

{
  "id": "1754289d-2979-4f74-922b-d4b334882126",
  "name": "Category name"
}

###
# @name getAllProducts
GET {{baseURL}}/products

###

# @name addProduct
POST {{baseURL}}/products
Content-Type: application/json

{
  "id": "1754289d-2979-4f74-922b-d4b375882126",
  "name": "Bike",
  "image": "http://placeimg.com/640/480/nature",
  "price": "972.00",
  "description": "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart"
}

###
# @name getProduct
GET {{baseURL}}/products/1754289d-2979-4f74-922b-d4b375882126

